# Generated by Django 5.1.7 on 2025-04-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('data_folder', models.CharField(max_length=200)),
                ('configuration_file', models.CharField(blank=True, max_length=400, null=True)),
                ('alias', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Data')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Data')),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestHourData',
            fields=[
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='instrument.instrument')),
                ('datetime', models.DateTimeField(null=True, verbose_name='DateTime')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestMinData',
            fields=[
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='instrument.instrument')),
                ('datetime', models.DateTimeField(null=True, verbose_name='DateTime')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500, null=True)),
                ('start_time', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End Date')),
                ('row_count', models.IntegerField(default=0, null=True)),
                ('error_num', models.IntegerField(default=0, null=True)),
                ('manual_load', models.BooleanField(default=False, null=True)),
                ('synced', models.BooleanField(default=False, null=True)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='instrument.instrument')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.units')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.FloatField(default=1, max_length=200)),
                ('offset', models.FloatField(default=0, max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('instrument_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.measurement')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='instrument.station'),
        ),
    ]
