# Generated by Django 5.1.7 on 2025-03-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_folder', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start Data')),
                ('end_date', models.DateTimeField(verbose_name='End Data')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('i', 'in progress'), ('c', 'complete'), ('e', 'error'), ('n', 'not started')], default='n', max_length=2)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.IntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrument')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.units')),
            ],
        ),
    ]
