# Generated by Django 5.1.7 on 2025-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmeasurement',
            name='alias',
            field=models.CharField(max_length=200),
        ),
    ]
