# Generated by Django 5.1.7 on 2025-03-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_alter_instrumentmeasurement_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='configuration_file',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='MeasurementCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.FloatField(default=1, max_length=200)),
                ('offset', models.FloatField(default=0, max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='Start Data')),
                ('instrument_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instrumentmeasurement')),
            ],
        ),
    ]
