# Generated by Django 5.1.7 on 2025-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_instrument_configuration_file_measurementcalibration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Data'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start Data'),
        ),
    ]
