# Generated by Django 5.1.7 on 2025-03-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0004_alter_instrument_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentmeasurement',
            name='max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='instrumentmeasurement',
            name='min',
            field=models.FloatField(default=0),
        ),
    ]
