# Generated by Django 5.1.7 on 2025-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0005_instrumentmeasurement_max_instrumentmeasurement_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='instrumentmeasurement',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
